
name: Python script Action mode 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  - cron: '0 */24 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a Python script from action
        run: python .github/workflows/example.py
